### ISSUE TITLE
How to set tooltip to MaterialLink in JAVA?

### ISSUE THREAD

**Issue by peggieHou** [GwtMaterialDesign/gwt-material#482]
I tried two ways to set tooltip in JAVA and both are not working and caused exception.
How could I do for it?
1. 
```
MaterialLink sideNavLink1 = new MaterialLink();
sideNavLink1.setIconType(IconType.HELP);
sideNavLink1.setIconColor("blue");
sideNavLink1.setTooltip("User Manual");
```
2.
```
MaterialTooltip sideNavTip1 = new MaterialTooltip();
sideNavTip1.setText("User Manual");
		
MaterialLink sideNavLink1 = new MaterialLink();
sideNavLink1.setIconType(IconType.HELP);
sideNavLink1.setIconColor("blue");
		
sideNavTip1.add(sideNavLink1);
```

Test 1 caused NullPointException and test 2 caused launching application failed.

**Comment by kevzlou7979** [comment]
Please can you enumerate what version of GMD are you using?

**Comment by peggieHou** [comment]
1.6.2. Thanks.

**Comment by kevzlou7979** [comment]
Also can you please send me the logs you've got.

**Comment by kevzlou7979** [comment]
Are you using GWTP or Errai? or just pure GWT as I can't reproduce it on my side. Note that we are also using Java Only on Errai.

**Comment by peggieHou** [comment]
Test 1 Log:
```
17:56:26.643 [ERROR] [prpo] Unable to load module entry point class com.tsmc.prpo.ui.client.PRPOEntryPointDispatcher (see associated exception for details)

com.google.web.bindery.event.shared.UmbrellaException: Exception caught: null
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:203)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEventFromSource(SimpleEventBus.java:96)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.fireEvent(PlaceManagerImpl.java:146)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.doRevealPlace(PlaceManagerImpl.java:121)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.revealPlace(PlaceManagerImpl.java:339)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.revealPlace(PlaceManagerImpl.java:320)
    at com.tsmc.prpo.ui.client.BootstrapperImpl.onBootstrap(BootstrapperImpl.java:24)
    at com.gwtplatform.mvp.client.ApplicationControllerImpl.init(ApplicationControllerImpl.java:11)
    at com.tsmc.prpo.ui.client.PRPOEntryPointDispatcher.revealCurrentPlace(PRPOEntryPointDispatcher.java:47)
    at com.tsmc.prpo.ui.client.PRPOEntryPointDispatcher.onModuleLoad(PRPOEntryPointDispatcher.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:411)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:526)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException: null
    at gwt.material.design.client.ui.MaterialTooltip.setText(MaterialTooltip.java:224)
    at com.tsmc.prpo.ui.client.presenter.GwtMaterialTodoView.&lt;init&gt;(GwtMaterialTodoView.java:128)
    at com.tsmc.prpo.ui.client.presenter.com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.com$tsmc$prpo$ui$client$presenter$GwtMaterialTodoView_com$tsmc$prpo$ui$client$presenter$GwtMaterialTodoView_methodInjection(com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java:786)
    at com.tsmc.prpo.ui.client.presenter.com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.get_Key$type$com$tsmc$prpo$ui$client$presenter$GwtMaterialTodoView$_annotation$$none$$(com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java:776)
    at com.tsmc.prpo.ui.client.presenter.com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.get_Key$type$com$tsmc$prpo$ui$client$presenter$GwtMaterialTodoPresenter$MyView$_annotation$$none$$(com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java:315)
    at com.tsmc.prpo.ui.client.presenter.com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.get_Key$type$com$tsmc$prpo$ui$client$presenter$GwtMaterialTodoPresenter$_annotation$$none$$(com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java:553)
    at com.tsmc.prpo.ui.client.presenter.com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment$5.get(com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java:574)
    at com.tsmc.prpo.ui.client.presenter.com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment$5.get(com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java:1)
    at com.gwtplatform.common.client.StandardProvider.get(StandardProvider.java:47)
    at com.gwtplatform.mvp.client.proxy.ProxyImpl.getPresenter(ProxyImpl.java:44)
    at com.gwtplatform.mvp.client.proxy.ProxyPlaceAbstract.handleRequest(ProxyPlaceAbstract.java:263)
    at com.gwtplatform.mvp.client.proxy.ProxyPlaceAbstract.access$2(ProxyPlaceAbstract.java:262)
    at com.gwtplatform.mvp.client.proxy.ProxyPlaceAbstract$1.onPlaceRequest(ProxyPlaceAbstract.java:201)
    at com.gwtplatform.mvp.client.proxy.PlaceRequestInternalEvent.dispatch(PlaceRequestInternalEvent.java:130)
    at com.gwtplatform.mvp.client.proxy.PlaceRequestInternalEvent.dispatch(PlaceRequestInternalEvent.java:1)
    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)
    at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEventFromSource(SimpleEventBus.java:96)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.fireEvent(PlaceManagerImpl.java:146)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.doRevealPlace(PlaceManagerImpl.java:121)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.revealPlace(PlaceManagerImpl.java:339)
    at com.gwtplatform.mvp.client.proxy.PlaceManagerImpl.revealPlace(PlaceManagerImpl.java:320)
    at com.tsmc.prpo.ui.client.BootstrapperImpl.onBootstrap(BootstrapperImpl.java:24)
    at com.gwtplatform.mvp.client.ApplicationControllerImpl.init(ApplicationControllerImpl.java:11)
    at com.tsmc.prpo.ui.client.PRPOEntryPointDispatcher.revealCurrentPlace(PRPOEntryPointDispatcher.java:47)
    at com.tsmc.prpo.ui.client.PRPOEntryPointDispatcher.onModuleLoad(PRPOEntryPointDispatcher.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:411)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:526)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:744)
```


Test 2 log:

```
com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) @gwt.material.design.client.ui.MaterialTooltip::command(Lcom/google/gwt/dom/client/Element;Ljava/lang/String;)([JavaScript object(103), string: 'remove']): Object doesn't support property or method 'remove'
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:203)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEventFromSource(SimpleEventBus.java:96)
    at com.gwtplatform.mvp.client.PresenterWidget.fireEvent(PresenterWidget.java:279)
    at com.gwtplatform.mvp.client.proxy.RevealRootContentEvent.fire(RevealRootContentEvent.java:48)
    at com.tsmc.prpo.ui.client.presenter.GwtMaterialTodoPresenter.revealInParent(GwtMaterialTodoPresenter.java:63)
    at com.gwtplatform.mvp.client.Presenter.forceReveal(Presenter.java:275)
    at com.gwtplatform.mvp.client.proxy.ProxyPlaceAbstract.manualReveal(ProxyPlaceAbstract.java:303)
    at com.gwtplatform.mvp.client.proxy.ProxyPlaceAbstract$3$1.execute(ProxyPlaceAbstract.java:283)
    at com.google.gwt.core.client.impl.SchedulerImpl$Task$.executeScheduled$(SchedulerImpl.java:50)
    at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:180)
    at com.google.gwt.core.client.impl.SchedulerImpl.flushPostEventPumpCommands(SchedulerImpl.java:345)
    at com.google.gwt.core.client.impl.SchedulerImpl$Flusher.execute(SchedulerImpl.java:78)
    at com.google.gwt.core.client.impl.SchedulerImpl.execute(SchedulerImpl.java:138)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:338)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:219)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:576)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:284)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) @gwt.material.design.client.ui.MaterialTooltip::command(Lcom/google/gwt/dom/client/Element;Ljava/lang/String;)([JavaScript object(103), string: 'remove']): Object doesn't support property or method 'remove'
    at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:87)
    at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:129)
    at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:354)
    at com.google.gwt.user.client.ui.Widget.setParent(Widget.java:484)
    at com.google.gwt.user.client.ui.Panel.adopt(Panel.java:124)
    at com.google.gwt.user.client.ui.ComplexPanel.add(ComplexPanel.java:105)
    at com.google.gwt.user.client.ui.AbsolutePanel.add(AbsolutePanel.java:97)
    at com.google.gwt.user.client.ui.Panel.add(Panel.java:68)
    at com.gwtplatform.mvp.client.RootPresenter$RootView.setInSlot(RootPresenter.java:95)
    at com.gwtplatform.mvp.client.PresenterWidget.setInSlot(PresenterWidget.java:378)
    at com.gwtplatform.mvp.client.PresenterWidget.setInSlot(PresenterWidget.java:340)
    at com.gwtplatform.mvp.client.RootPresenter.onRevealRootContent(RootPresenter.java:187)
    at com.gwtplatform.mvp.client.proxy.RevealRootContentEvent.dispatch(RevealRootContentEvent.java:72)
    at com.gwtplatform.mvp.client.proxy.RevealRootContentEvent.dispatch(RevealRootContentEvent.java:1)
    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)
    at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEventFromSource(SimpleEventBus.java:96)
    at com.gwtplatform.mvp.client.PresenterWidget.fireEvent(PresenterWidget.java:279)
    at com.gwtplatform.mvp.client.proxy.RevealRootContentEvent.fire(RevealRootContentEvent.java:48)
    at com.tsmc.prpo.ui.client.presenter.GwtMaterialTodoPresenter.revealInParent(GwtMaterialTodoPresenter.java:63)
    at com.gwtplatform.mvp.client.Presenter.forceReveal(Presenter.java:275)
    at com.gwtplatform.mvp.client.proxy.ProxyPlaceAbstract.manualReveal(ProxyPlaceAbstract.java:303)
    at com.gwtplatform.mvp.client.proxy.ProxyPlaceAbstract$3$1.execute(ProxyPlaceAbstract.java:283)
    at com.google.gwt.core.client.impl.SchedulerImpl$Task$.executeScheduled$(SchedulerImpl.java:50)
    at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:180)
    at com.google.gwt.core.client.impl.SchedulerImpl.flushPostEventPumpCommands(SchedulerImpl.java:345)
    at com.google.gwt.core.client.impl.SchedulerImpl$Flusher.execute(SchedulerImpl.java:78)
    at com.google.gwt.core.client.impl.SchedulerImpl.execute(SchedulerImpl.java:138)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:338)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:219)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:576)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:284)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by peggieHou** [comment]
Yes. We used GWT 2.6.1 + GWTP 1.3.1 in JAVA.

**Comment by kevzlou7979** [comment]
Try upgrading yout GWT to 2.7.0 as it's one of requirements on GMD 1.x

**Comment by peggieHou** [comment]
OK! I'll try it out. Thanks!

**Comment by peggieHou** [comment]
It works when upgrade to GWT2.7. Thanks!
