### ISSUE TITLE
gwt-material 2.0-rc3 fails when app is running in Dev Mode

### ISSUE THREAD

**Issue by Waine** [GwtMaterialDesign/gwt-material#561]
This was not the case for 1.6.x. As far as I understand the issue is connected with the fact that JsMaterialElement.displayEffect() method is exposed using JsInterop now. Is it possible to make it work correctly in Dev Mode?

Exception stack trace example:

Caused by: com.google.gwt.core.client.JavaScriptException: (Error) @gwt.material.design.client.js.JsMaterialElement::displayEffect()([]): Unable to find named method on window 	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:252) 	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:121) 	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:573) 	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:315) 	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:107) 	at gwt.material.design.client.js.JsMaterialElement.displayEffect(JsMaterialElement.java) 	at gwt.material.design.client.base.Waves.detectAndApply(Waves.java:34) 	at gwt.material.design.client.base.Waves.lambda$0(Waves.java:46) 	at com.google.gwt.event.logical.shared.AttachEvent.dispatch(AttachEvent.java:100) 	at com.google.gwt.event.logical.shared.AttachEvent.dispatch(AttachEvent.java:1) 	at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1) 	at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40) 	at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193) 	at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88) 	at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:127) 	at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:129) 	at com.google.gwt.event.logical.shared.AttachEvent.fire(AttachEvent.java:52) 	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:360) 	at com.google.gwt.user.client.ui.AttachDetachException$1.execute(AttachDetachException.java:34) 	at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:74) 	at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:129) 	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:354) 	at com.google.gwt.user.client.ui.AttachDetachException$1.execute(AttachDetachException.java:34) 	at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:74) 	at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:129) 	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:354) 	at com.google.gwt.user.client.ui.AttachDetachException$1.execute(AttachDetachException.java:34) 	at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:74) 	at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:129) 	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:354) 	at com.google.gwt.user.client.ui.AttachDetachException$1.execute(AttachDetachException.java:34) 	at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:74) 	at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:129) 	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:354) 	at com.google.gwt.user.client.ui.AttachDetachException$1.execute(AttachDetachException.java:34) 	at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:74) 	at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:129) 	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:354) 	at com.google.gwt.user.client.ui.AttachDetachException$1.execute(AttachDetachException.java:34) 	at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:74) 	at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:129) 	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:354) 	at com.google.gwt.user.client.ui.Composite.onAttach(Composite.java:179) 	at com.google.gwt.user.client.ui.Widget.setParent(Widget.java:484) 	at com.google.gwt.user.client.ui.Panel.adopt(Panel.java:124) 	at com.google.gwt.user.client.ui.ComplexPanel.add(ComplexPanel.java:105) 	at com.google.gwt.user.client.ui.AbsolutePanel.add(AbsolutePanel.java:99) 	at com.eakonovalov.client.Webapp.lambda$0(Webapp.java:36) 	at com.google.gwt.core.client.impl.SchedulerImpl.execute(SchedulerImpl.java:141) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103) 	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72) 	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172) 	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:341) 	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:222) 	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:121) 	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:573) 	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293) 	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91) 	at com.google.gwt.core.client.impl.Impl.apply(Impl.java) 	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:291) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103) 	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72) 	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172) 	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296) 	at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551) 	at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368) 	at java.lang.Thread.run(Thread.java:745)

**Comment by kevzlou7979** [comment]
Can you confirm if the 2.0-SNAPSHOT works well because I think it was fixed recently with this issue https://github.com/GwtMaterialDesign/gwt-material/issues/539. Can you test if it works. Thanks for catching this up

**Comment by BenDol** [comment]
2.0 only supports GWT 2.8.0+

**Comment by Waine** [comment]
Have checked 2.0-SNAPSHOT - the same result. Compiled app works fine, but fails under Dev Mode.
I compile and run application in Dev Mode using GWT 2.8.0

**Comment by kevzlou7979** [comment]
@Waine Whats the version of your java?

**Comment by Waine** [comment]
I use latest java:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by kevzlou7979** [comment]
Thanks for the response, Could you share a basic project because I can't reproduce on my side. You can zip the project and attached here I think.

**Comment by hellofornow** [comment]
I'm purely speculating here, but @Waine is it possible that when you run super-dev (through maven or gradle) you're not specifying "generateJsInteropExports"?

**Comment by Vadirajachar** [comment]
Did anyone find a resolution for this issue? I am facing the same issue where I am unable to run classic-dev mode. 

I am using JRE1.8.0_181
GWT 2.8.1

Stacktrace from Eclipse console is copied below - 

08:03:23.267 [ERROR] [gwtcuriosity] Your carousel container is not yet initialized
java.lang.IllegalStateException: null
    at gwt.material.design.addins.client.carousel.MaterialCarousel.command(MaterialCarousel.java:275)
    at gwt.material.design.addins.client.carousel.MaterialCarousel.add(MaterialCarousel.java:206)
    at org.vadiraj.curiosity.client.GWTCuriosity.onModuleLoad(GWTCuriosity.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:423)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:530)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
    at java.lang.Thread.run(Unknown Source)
