### ISSUE TITLE
Data Table error

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#612]
I download
https://github.com/GwtMaterialDesign/gwt-material-demo.git 
Compile and run

1)Then go to  Data Table page
2)Change page
3) Return to Data Table again

```
ConsoleLogger.java:32 It is recommended that an InfiniteDataView only use a remote sorting DataSource, this will be set for you.
ConsoleLogger.java:32 Exception caught: 5 exceptions caught: Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined
ConsoleLogger.java:55 Exception: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: 5 exceptions caught: Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined
ConsoleLogger.java:32 Error: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: 5 exceptions caught: Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined
    at Uid_g$.yA_g$ [as createError_0_g$] (Throwable.java:121)
    at Uid_g$.IA_g$ [as initializeBackingError_0_g$] (Throwable.java:113)
    at Uid_g$.sA_g$ (Throwable.java:74)
    at Uid_g$.YA_g$ (Exception.java:33)
    at Uid_g$.eB_g$ (RuntimeException.java:33)
    at Uid_g$.O8b_g$ (UmbrellaException.java:65)
    at Uid_g$.V8b_g$ (UmbrellaException.java:26)
    at Uid_g$ (AttachDetachException.java:136)
    at Wid_g$ (AttachDetachException.java:87)
    at ehf_g$.Ehd_g$ [as doAttachChildren_0_g$] (Panel.java:129)
    at ehf_g$.kQc_g$ [as onAttach_0_g$] (Widget.java:354)
    at ehf_g$.sQc_g$ [as setParent_0_g$] (Widget.java:484)
    at kyd_g$.Chd_g$ [as adopt_1_g$] (Panel.java:124)
    at kyd_g$.Ohd_g$ [as add_6_g$] (ComplexPanel.java:105)
    at kyd_g$.myd_g$ [as add_4_g$] (HTMLPanel.java:153)
    at s8g_g$.bFe_g$ [as setInSlot_4_g$] (ViewImpl.java:93)
    at g8g_g$.$De_g$ [as setInSlot_1_g$] (PresenterWidget.java:509)
    at g8g_g$.ZDe_g$ [as setInSlot_0_g$] (PresenterWidget.java:477)
    at PPe_g$.QPe_g$ [as execute_1_g$] (RevealContentHandler.java:67)
    at wM_g$ (SchedulerImpl.java:50)
    at aM_g$ (SchedulerImpl.java:183)
    at RL_g$.XL_g$ [as flushPostEventPumpCommands_0_g$] (SchedulerImpl.java:347)
    at nM_g$.oM_g$ [as execute_2_g$] (SchedulerImpl.java:78)
    at UL_g$ (SchedulerImpl.java:141)
    at HK_g$ (Impl.java:239)
    at KK_g$ (Impl.java:291)
    at Impl.java:77
    at callback_0_g$ (SchedulerImpl.java:196)
ConsoleLogger.java:55 Caused by: com.google.gwt.user.client.ui.AttachDetachException: 5 exceptions caught: Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined; Exception caught: Exception caught: undefined
```
![demo1](https://cloud.githubusercontent.com/assets/439337/24958852/791a81c6-1f99-11e7-9250-fc3d986e5d4a.png)

Maybe that's why I have a similar error
I can not delete the columns in MaterialDataTable

I open presenter add columns, then delete  them, all ok.

But when so such:
1)Open presenter with MaterialDataTable 
2) add columns 
3) then change presenter
4) Return to presenter with MaterialDataTable 
5) Try delete columns I have such error

```
java.lang.IndexOutOfBoundsException
     at Unknown.Rhb_g$(Throwable.java:61)
     at Unknown.vib_g$(Exception.java:25)
     at Unknown.Dib_g$(RuntimeException.java:25)
     at Unknown.T2f_g$(IndexOutOfBoundsException.java:25)
     at Unknown.Wse_g$(WidgetCollection.java:112)
     at Unknown.JRd_g$(ComplexPanel.java:36)
     at Unknown.QRd_g$(ComplexPanel.java:56)
     at Unknown.Jof_g$(AbstractDataView.java:971)
     at Unknown.NYf_g$(AbstractDataTable.java:448)
     at Unknown.R$f_g$(MaterialDataTable.java:212)
     at Unknown.QXi_g$(ConsoleTable.java:173)
     at Unknown.Do_g$(ClientsView.java:116)
     at Unknown.Zm_g$(ClientsPresenter.java:99)
     at Unknown.ab_g$(PresenterWidget.java:574)
     at Unknown.qb_g$(PresenterWidget.java:378)
     at Unknown.pb_g$(PresenterWidget.java:347)
     at Unknown.ZWe_g$(RevealContentHandler.java:60)
     at Unknown.dXe_g$(RevealContentHandler.java:58)
     at Unknown.Esb_g$(SchedulerImpl.java:50)
     at Unknown.isb_g$(SchedulerImpl.java:183)

```

```
    public void clearColumns() {
        logger.info(consoleTable.getColumns().size() + "");
        while (consoleTable.getColumns().size() > 0)
            consoleTable.removeColumn(0);
        logger.info(consoleTable.getColumns().size() + "");
    }
```

**Comment by kevzlou7979** [comment]
Duplicate https://github.com/GwtMaterialDesign/gwt-material-table/issues/48
