### ISSUE TITLE
MaterialDatePicker setLanguage exception

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material#705]
Hi, 
1)  the DatePicker throws an exception if you change the language.
```
 bDayDate.setLanguage(DatePickerLanguage.DE);
```
Exception:
```
  >Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'stop' of undefined
    TypeError: Cannot read property 'stop' of undefined
    at u2f_g$.M3f_g$ [as setLanguage_0_g$] (App-0.js:85101:26)
    at new s0i_g$ (App-0.js:128663:21)
    ...
    ...
    ...
```
2) What is the name of the new function for the old.
```
bDayDate.reinitialize();
```
using Snapshot gwt-material-2.0-20171015.002523-448.jar

Thanks

**Comment by kevzlou7979** [comment]
You can call
```
bDayDate.reload();
```

**Comment by simerlec** [comment]
Hey,
I have the same issue as mentioned in @HoochSDS's first point. Setting the language causes an exception.

```
TypeError: Cannot read property 'stop' of undefined
    at vsh_g$.Nth_g$ [as setLanguage_2_g$] (MaterialDatePicker.java:446)
    ...
```

kr

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/73db9d850718bf6ae46b541ea30b7b849195de20
