### ISSUE TITLE
Updating to material-gwt 2.0 creates exceptions in MaterialDropDown.

### ISSUE THREAD

**Issue by mtmmtm9** [GwtMaterialDesign/gwt-material#737]
I updated from r2.0-c6. It created this exception when starting:

Exception caught: undefined
  at com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: 2 exceptions caught: Exception caught: undefined; Exception caught: undefined
  at com.google.gwt.user.client.ui.AttachDetachException: Exception caught: 2 exceptions caught: Exception caught: undefined; Exception caught: undefined
  at com.google.gwt.user.client.ui.AttachDetachException: 2 exceptions caught: Exception caught: undefined; Exception caught: undefined
  at com.google.gwt.user.client.ui.AttachDetachException: Exception caught: undefined
  at java.lang.IndexOutOfBoundsException
  at java.lang.IndexOutOfBoundsException
  at Unknown.Throwable(Throwable.java:60)
  at Unknown.Exception(Exception.java:25)
  at Unknown.RuntimeException(RuntimeException.java:25)
  at Unknown.IndexOutOfBoundsException(IndexOutOfBoundsException.java:25)
  at Unknown.get_16(WidgetCollection.java:112)
  at Unknown.getWidget(ComplexPanel.java:36)
  at Unknown.lambda$0_28(MaterialDropDown.java:118)
  at Unknown.accept_19(MaterialDropDown.java:115)
  at Unknown.$forEach(Iterable.java:39)
  at Unknown.forEach_4(Iterable.java:36)
  at Unknown.registerDropdownItemHandlers(MaterialDropDown.java:115)
  at Unknown.onLoad_6(MaterialDropDown.java:111)
  at Unknown.onAttach_1(Widget.java:359)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.onAttach_3(Composite.java:179)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.onAttach_3(Composite.java:179)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.setParent(Widget.java:484)
  at Unknown.adopt(Panel.java:124)
  at Unknown.insert_7(LayoutPanel.java:198)
  at Unknown.add_19(LayoutPanel.java:134)
  at Unknown.initialize(ConfigTool.java:381)
  at Unknown.onSuccess_43(GUIHelper.java:46)
  at Unknown.onSuccess_44(GUIHelper.java:40)
  at Unknown.onSuccess_0(CallWrapper.java:26)
  at Unknown.onResponseReceived(RequestCallbackAdapter.java:232)
  at Unknown.fireOnResponseReceived(Request.java:250)
  at Unknown.onReadyStateChange(RequestBuilder.java:412)
  at Unknown.anonymous(XMLHttpRequest.java:329)
  at Unknown.apply_0(Impl.java:309)
  at Unknown.entry0(Impl.java:361)
  at Unknown.anonymous(Impl.java:78)
Caused by: java.lang.IndexOutOfBoundsException
  at Unknown.Throwable(Throwable.java:60)
  at Unknown.Exception(Exception.java:25)
  at Unknown.RuntimeException(RuntimeException.java:25)
  at Unknown.IndexOutOfBoundsException(IndexOutOfBoundsException.java:25)
  at Unknown.get_16(WidgetCollection.java:112)
  at Unknown.getWidget(ComplexPanel.java:36)
  at Unknown.lambda$0_28(MaterialDropDown.java:118)
  at Unknown.accept_19(MaterialDropDown.java:115)
  at Unknown.$forEach(Iterable.java:39)
  at Unknown.forEach_4(Iterable.java:36)
  at Unknown.registerDropdownItemHandlers(MaterialDropDown.java:115)
  at Unknown.onLoad_6(MaterialDropDown.java:111)
  at Unknown.onAttach_1(Widget.java:359)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.onAttach_3(Composite.java:179)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.onAttach_3(Composite.java:179)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.execute_4(AttachDetachException.java:34)
  at Unknown.tryCommand(AttachDetachException.java:74)
  at Unknown.doAttachChildren_0(Panel.java:129)
  at Unknown.onAttach_1(Widget.java:354)
  at Unknown.setParent(Widget.java:484)
  at Unknown.adopt(Panel.java:124)
  at Unknown.insert_7(LayoutPanel.java:198)
  at Unknown.add_19(LayoutPanel.java:134)
  at Unknown.initialize(ConfigTool.java:381)
  at Unknown.onSuccess_43(GUIHelper.java:46)
  at Unknown.onSuccess_44(GUIHelper.java:40)
  at Unknown.onSuccess_0(CallWrapper.java:26)
  at Unknown.onResponseReceived(RequestCallbackAdapter.java:232)
  at Unknown.fireOnResponseReceived(Request.java:250)
  at Unknown.onReadyStateChange(RequestBuilder.java:412)
  at Unknown.anonymous(XMLHttpRequest.java:329)
  at Unknown.apply_0(Impl.java:309)
  at Unknown.entry0(Impl.java:361)
  at Unknown.anonymous(Impl.java:78)

It might be a problem in MaterialDropDown:

protected void registerDropdownItemHandlers() {
        getChildren().forEach(widget -> {
            if (widget instanceof ListItem) {
                ListItem item = (ListItem) widget;
                if (item.getWidget(0) instanceof MaterialWidget) {
                    MaterialWidget child = (MaterialWidget) item.getWidget(0);
                    registerHandler(child.addDomHandler(event -> {
                        SelectionEvent.fire(MaterialDropDown.this, child);
                    }, ClickEvent.getType()));
                }
            }
        });
    }

item.getWidget(0) might not have any data.

**Comment by kevzlou7979** [comment]
Ok so your dropdown adds an empty ListItem.
i.e.

```java

dropdown.add(new ListItem());

```

So in conclusion we need a thorough condition check into registration of handler, thanks for the catch. Will update it - will do a release of 2.0.1 for all the bugs regarding 2.0.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/5b1901c37a12458278729f8f3169071ab6467eab
